danielfm/pybreaker

.gitignore, src/pybreaker.py, src/tests.py
.next() has been renamed to __next__() in Python3. Due to this issue the generator functions / tests could not be executed in Python3.5. 
Also the assertRaises test required a lambda function to have the next statement executed to be able to raise the exception.
=> Fixed generator issue / tests for Python3.5

src/pybreaker.py, src/tests.py
When the circuit breaker is open:
cb.call() delegates to CircuitOpenState.call() which is not implemented so the parent CircuitBreakerState.call() is called.
This function calls CircuitOpenState.before_call() and then call the wrapped function.
CircuitOpenState.before_call() switch the state of the CB to half open and then calls cb.call(), which in turn delegates to CircuitHalfOpenState.call() which is not implemented so we go back to CircuitBreakerState.call() which eventually calls the wrapped function a second time (from a timeline perspective this is actually the first call)
I updated a testcase to illustrate the issue and propose a solution.
=> Wrapped function is called twice during successful call in open state

.travis.yml, src/tests.py
When running the tests, found (what appears to be) an artifact of the cleanup in c046c2f. Also added a travis config since I've found that helpful in the past - I can split up this PR as well if the travis config doesn't make sense.
A passing build can be found here: https://travis-ci.org/phillbaker/pybreaker/builds/214252529
=> Add travis config & fix test reference

src/pybreaker.py, src/tests.py
Fixes a bug wherein the `name` property in `CircuitBreakerStorage` did not reference an existent variable.
=> Fixes a bug in the name property in CircuitBreakerStorage

README.rst, setup.py, src/pybreaker.py, src/tests.py
* Allows keys to be namespaced
* On failure of redis, uses a fallback state (defaults to closed, ie allowing calls through)
* Separates the tests into mixins to be tested against different storage backends (sorry the diff is hard to read).
Questions:
* What do you think about logging the connection failures (so they're not totally invisible)?
* The current code should handle some concurrency - e.g. incrementing the counter at the same time or setting the opened_at timestamp at the same time, in cases where locking is done in local memory, what are your thoughts on translating that to Redis?
Remaining work:
=> Add redis-backed storage class.

README.rst, src/pybreaker.py
Should close https://github.com/danielfm/pybreaker/issues/16.
Not sure how to write a test for this, I couldn't get the test environment to _not_ install redis. But I did test this locally and it seemed to work better.
=> Move import of redis into `CircuitRedisStorage.__init__`

setup.py, src/pybreaker.py, src/tests.py
I'm a big fan of your library and I've been using my own fork over here at SeatGeek, so I figured I'd contribute. We use Tornado as our webserver and use this code to circuit break asynchronous code.  
This change adds optional support for Tornado coroutines. This should be a backwards compatible change. 
I did this by:
- Modifying `CircuitBreaker.__call__` to optionally take a keyword argument `__pybreaker_call_async`, which will call `CircuitBreaker.call_async` if `True`. The keyword argument is sufficiently verbose to hopefully avoid collision with existing keyword arguments
- Adding `CircuitBreaker.call_async`
- Adding `CircuitBreakerState.call_async`
- Duplicating the import pattern used by HAS_REDIS_SUPPORT 
This also has tests that cover the parts that I added. It also fixes a bug …
=> Add optional support for calling Tornado coroutines

CHANGELOG, setup.py, src/pybreaker.py, src/tests.py
The PR intends to resolve danielfm/pybreak#26 by altering the `CircuitBreaker` to make no assumptions about an initialized `CircuitBreaker` state. Instead, on first call of `breaker.state`, the state is retrieved from the `state_storage`. This allows `pybreaker` to play nicely in environments where it is desirable share `CircuitBreaker` state between machines.
=> Get initial CircuitBreaker state from state_storage

src/pybreaker.py, src/tests.py
The current CircuitBreaker code currently correctly detects the current
state from the provided state storage object and uses it to construct
the internal state object. However when the detected state is "closed",
the newly instantiated `CircuitClosedState` will reset the fail counter
on the breaker.
These changes move the `reset_counter()` call into the notify block.
This issue was called out in #26, but was not addressed in #27.
=> Do not reset fail count in CircuitBreaker creation

setup.py, src/pybreaker.py, src/tests.py
When using python 2.7, the trigger exception is lost when the CB's threshold breaches and CB's in half-open status and failed on the retry.
=> Add trigger exception into the CircuitBreakerError

src/pybreaker.py, src/tests.py
Hi! I was testing how pybreaker would behave in various scenarios where state is being stored on Redis and the Redis server misbehaves. `CircuitRedisStorage` will handle intermittent and complete connection loss with the Redis server in an acceptable manner. But it doesn't handle data loss on the Redis server gracefully (it always expects to find the state on Redis).
This change modifies the `state` property so that if it appears that state on Redis was lost, it will try to setup the state on Redis again with the initial circuit breaker state.
=> Re-initialize state on Redis if missing

src/pybreaker.py, src/tests.py
We discovered a bug in the circuit breaker logic that updates the `opened_at` value for the storage state as new processes spin up and initialize that state. The consequence of this is that we can inadvertently extend the timeout window for an open circuit indefinitely if new processes spin up more frequently than the timeout configured.
This fix moves the setting of the `opened_at` time to `CircuitBreaker.open()` so that it gets set only when the breaker opens and not when the `CircuitBreakerState` is instantiated (which can happen without an attempt to call the function wrapped).
=> Fix bug with timeout window growing as additional breakers are defined

.travis.yml, setup.py
The Travis build is broken at present due to two issues:
a) Tornado 5 has dropped Python 3.3 support
b) redis & fakeredis have both seen updates that cause dependency version conflicts
This fixes (a) by applying similar behaviour as is already in place for Python 3.2, and (b) by locking the dependency versions to those used in the last successful builds.
=> Fix travis build

.travis.yml, setup.py, src/tests.py
This adds a Travis build for Python 3.7, and fixes a test assertions where the behaviour was broken due to the [PEP 479](https://www.python.org/dev/peps/pep-0479/) changes to StopIteration (this doesn't appear to affect the behaviour, just the test).
This depends on #37.
=> Add Python 3.7 support

README.rst, src/pybreaker.py, src/tests.py
This PR changes the excluded exceptions list to allow a mix of exception types and callable functions, so as to allow for more fine-grained filtering of system exceptions.
This covers cases such as [Bottle's](https://bottlepy.org/) `HTTPError`, where the same exception is used to cover both client errors (HTTP 4xx) and server exceptions (HTTP 5xx). We don't wish to increment the failure counter in cases where we're proxying a request that may cause a client error (e.g. a 404) - hence passing a filter function allows us to differentiate the different uses of this exception type.
=> Allow filter functions to be used for excluded exceptions

.gitignore
This merely adds `.gitignore` entires for [VirtualEnv](https://virtualenv.pypa.io/en/stable/) and [Visual Studio Code](https://code.visualstudio.com).
=> Add .gitignore entries for VirtualEnv/VSCode

src/pybreaker.py
According to PEP 479 documentation (https://www.python.org/dev/peps/pep-0479/#examples-of-breakage), when `StopIteration` occurs, the generator should end with a `return` statement instead of a `raise`.
See the following example from PEP 479:
> More complicated iteration patterns will need explicit try/except constructs. For example, a hypothetical parser like this:
```
def parser(f):
while True:
data = next(f)
while True:
line = next(f)
if line == "- end -": break
data += line
yield data
```
> would need to be rewritten as:
```
def parser(f):
while True:
try:
data = next(f)
while True:
line = next(f)
if line == "- end -": break
data += line
yield data
except StopIteration:
return
```
=> Replace raise with return per PEP 479 recommendations

src/tests.py
Previously, the tests were importing `pytest` and using it for a `fail` call.
This causes issues when running the repository from scratch, because setup.py doesn't include a pytest dependency. 
The alternative to this approach would be adding the dependency, but since it's only used in one place I assumed you'd rather keep the codebase minimal.
Tested by running `python setup.py test` in a fresh virtualenv before and after.
=> Replace pytest.fail with TestCase.fail to minimize dependency

src/pybreaker.py, src/tests.py
Fix for https://github.com/danielfm/pybreaker/issues/60
The setting lets you alter the default behaviour of throwing a new CircuitBreakerError every time the circuit opens. By setting THROW_NEW_ERROR_ON_TRIP to False, the original exception will be preserved when the circuit breaker opens
The default value for this setting is True, which mimics the current behaviour of the library.
=> Adding settings to allow passing THROW_NEW_ERROR_ON_TRIP

setup.py
This makes PR avoids issues with `pip` package resolution.
Consider that support for Python 3.6 is removed, when `pybreaker` is installed on Python 3.6, if we don't add this, it will fail, as the latest version will be installed.
See more on https://packaging.python.org/en/latest/guides/distributing-packages-using-setuptools/#python-requires.
=> Add `python_requires` on setup.py

src/pybreaker.py
This PR just removes the redundancy on the `redis` import. Above the removed `try..except` we can see the following:
https://github.com/danielfm/pybreaker/blob/2f6c730d21c2334c33c85ef7927d261ff81d3a20/src/pybreaker.py#L477-L478
=> Remove redundant `redis` import check

.github/workflows/actions.yml, README.rst, setup.py
Python 3.6 has reached EOL last year: https://endoflife.date/python
=> Drop Python 3.6 support

.pre-commit-config.yaml, setup.py, src/pybreaker.py, src/tests.py
- Add `pre-commit` configuration file.
- Add [`isort`](https://pycqa.github.io/isort/) to sort import statements.
- Add [`black`](https://github.com/psf/black) to format code.
- Remove `#-*- coding:utf-8 -*-` because it's not needed anymore.
=> Add linter & format setup

src/pybreaker.py
I'd like to add type annotation on the whole module. Would you mind? Python 3.6 supports it just fine. 😗
=> Improve type annotation on `CircuitBreakerState`

src/pybreaker.py
=> Fix `state` parameter type hint on `CircuitRedisStorage.__init__`

CHANGELOG, README.rst, setup.py, src/pybreaker/__init__.py, src/tests.py
This adds a new `calling()` method to `CircuitBreaker`. This method returns a context manager, enabling the circuit breaker to be used with a `with` statement. The block of code inside the `with` statement will be executed according to the rules implemented by the current state of the circuit breaker.
Fixes: https://github.com/danielfm/pybreaker/issues/85
Example usage:
```
db_breaker = CircuitBreaker()
with db_breaker.calling():
pass
```
Initially, I attempted to make the `CircuitBreaker` itself a context manager, by implementing `__enter__` and `__exit__` in the class itself, but this required an amount of refactoring that I was not comfortable with. Therefore, I opted to implement this on top of the existing `call` method.
As for the naming of the new method, I took inspiration from …
=> Add calling() method to CircuitBreaker, returning a context manager

src/pybreaker/__init__.py
Supersedes danielfm/pybreaker#92, which switched to UTC-based datetimes (aware), but didn't extend that adjustment to reading the timestamp from Redis.
=> Convert datetime.utcnow -> datetime.now(UTC)

.gitignore, src/pybreaker/__init__.py, tests/pybreaker_test.py
- Add success_threshold parameter to CircuitBreaker constructor (default: 1 for backward compatibility)
- Add success_counter property to track consecutive successes in half-open state
- Update CircuitBreakerStorage interface to support success counter operations
- Implement success counter in CircuitMemoryStorage and CircuitRedisStorage
- Modify CircuitHalfOpenState to increment success counter and only close when threshold is reached
- Reset success counter when circuit opens or closes
- Add tests for success threshold functionality
- Fix test_namespace to expect 3 Redis keys (fail_counter, success_counter, state)
=> Add success_threshold parameter 
